name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: dfinity/setup-dfx@main
        with:
          dfx-version: '0.31.0'

      - uses: dfinity/setup-mops@main

      - name: install mops packages
        run: mops install

      - name: Download binaries
        run: dfx build --check

      - name: run tests
        run: dfx cache show && mops test